version: "3.8"

services:
  pyqt_app:
    build: .
    container_name: orora_tech_proj  # Ensures the container name remains consistent
    env_file:
      - .env
    volumes:
      - .:/app  # Bind mount: Maps current directory to /app in the container
    stdin_open: true
    tty: true
    ports:
      - "8085:8085"
    network_mode: "bridge"  # Ensures networking is properly configured
    extra_hosts:
      - "host.docker.internal:host-gateway"
